[2025-04-05T15:49:18.988+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:49:18.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:49:18.991+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:49:18.991+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:49:20.195+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:49:20.193+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:49:20.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:49:20.207+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 1.225 seconds
[2025-04-05T15:49:50.272+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:49:50.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:49:50.275+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:49:50.275+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:49:50.627+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:49:50.624+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:49:50.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:49:50.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.374 seconds
[2025-04-05T15:50:20.744+0000] {processor.py:161} INFO - Started process (PID=128) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:50:20.745+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:50:20.747+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:50:20.747+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:50:21.085+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:50:21.082+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:50:21.085+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:50:21.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.359 seconds
[2025-04-05T15:50:51.152+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:50:51.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:50:51.155+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:50:51.155+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:50:51.518+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:50:51.515+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:50:51.519+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:50:51.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.387 seconds
[2025-04-05T15:51:21.776+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:51:21.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:51:21.779+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:51:21.779+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:51:22.244+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:51:22.241+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:51:22.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:51:22.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.491 seconds
[2025-04-05T15:51:52.547+0000] {processor.py:161} INFO - Started process (PID=158) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:51:52.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:51:52.550+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:51:52.549+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:51:52.961+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:51:52.958+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:51:52.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:51:52.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.437 seconds
[2025-04-05T15:52:23.236+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:52:23.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:52:23.238+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:52:23.238+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:52:23.559+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:52:23.556+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:52:23.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:52:23.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.338 seconds
[2025-04-05T15:52:53.811+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:52:53.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:52:53.813+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:52:53.813+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:52:54.139+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:52:54.136+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:52:54.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:52:54.150+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.343 seconds
[2025-04-05T15:54:09.279+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:54:09.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:54:09.286+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:54:09.285+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:54:11.258+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:54:11.253+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:54:11.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:54:11.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 2.011 seconds
[2025-04-05T15:54:41.481+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:54:41.482+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:54:41.484+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:54:41.483+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:54:41.737+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:54:41.734+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:54:41.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:54:41.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.278 seconds
[2025-04-05T15:55:12.013+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:55:12.015+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:55:12.017+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:55:12.017+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:55:12.266+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:55:12.263+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:55:12.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:55:12.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.273 seconds
[2025-04-05T15:55:42.517+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:55:42.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:55:42.520+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:55:42.520+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:55:42.926+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:55:42.924+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:55:42.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:55:42.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.426 seconds
[2025-04-05T15:56:13.179+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:56:13.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:56:13.182+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:56:13.181+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:56:13.554+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:56:13.551+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:56:13.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:56:13.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.392 seconds
[2025-04-05T15:56:43.811+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:56:43.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:56:43.814+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:56:43.813+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:56:44.141+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:56:44.139+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:56:44.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:56:44.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.346 seconds
[2025-04-05T15:57:14.435+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:57:14.436+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:57:14.438+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:57:14.437+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:57:14.781+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:57:14.778+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:57:14.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:57:14.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.365 seconds
[2025-04-05T15:57:45.052+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:57:45.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:57:45.055+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:57:45.055+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:57:45.379+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:57:45.376+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:57:45.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:57:45.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.345 seconds
[2025-04-05T15:58:15.643+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:58:15.644+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:58:15.647+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:58:15.646+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:58:15.876+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:58:15.873+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:58:15.876+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:58:15.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.253 seconds
[2025-04-05T15:58:46.131+0000] {processor.py:161} INFO - Started process (PID=128) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:58:46.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:58:46.133+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:58:46.133+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:58:46.484+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:58:46.481+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:58:46.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:58:46.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.369 seconds
[2025-04-05T15:59:46.732+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:59:46.734+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T15:59:46.739+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:59:46.738+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:59:49.012+0000] {logging_mixin.py:188} INFO - [2025-04-05T15:59:49.004+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T15:59:49.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T15:59:49.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 2.329 seconds
[2025-04-05T16:00:19.294+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:00:19.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:00:19.298+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:00:19.297+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:00:19.556+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:00:19.553+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:00:19.557+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:00:19.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.284 seconds
[2025-04-05T16:00:49.852+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:00:49.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:00:49.856+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:00:49.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:00:50.113+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:00:50.110+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:00:50.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:00:50.128+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.285 seconds
[2025-04-05T16:01:20.383+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:01:20.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:01:20.386+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:01:20.386+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:01:20.852+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:01:20.849+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:01:20.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:01:20.866+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.487 seconds
[2025-04-05T16:01:51.119+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:01:51.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:01:51.121+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:01:51.120+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:01:51.477+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:01:51.474+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:01:51.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:01:51.488+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.374 seconds
[2025-04-05T16:02:21.773+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:02:21.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:02:21.777+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:02:21.776+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:02:22.164+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:02:22.161+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:02:22.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:02:22.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.420 seconds
[2025-04-05T16:02:52.454+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:02:52.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:02:52.457+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:02:52.457+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:02:52.795+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:02:52.793+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:02:52.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:02:52.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.358 seconds
[2025-04-05T16:03:23.063+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:03:23.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:03:23.066+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:03:23.065+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:03:23.392+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:03:23.389+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:03:23.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:03:23.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.347 seconds
[2025-04-05T16:03:53.687+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:03:53.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:03:53.691+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:03:53.690+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:03:53.944+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:03:53.941+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:03:53.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:03:53.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.280 seconds
[2025-04-05T16:04:24.231+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:04:24.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:04:24.234+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:04:24.233+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:04:24.559+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:04:24.556+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:04:24.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:04:24.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.343 seconds
[2025-04-05T16:04:54.848+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:04:54.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:04:54.851+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:04:54.851+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:04:55.174+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:04:55.171+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:04:55.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:04:55.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.343 seconds
[2025-04-05T16:05:25.437+0000] {processor.py:161} INFO - Started process (PID=139) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:05:25.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:05:25.439+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:05:25.439+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:05:25.772+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:05:25.770+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:05:25.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:05:25.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.351 seconds
[2025-04-05T16:05:56.091+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:05:56.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:05:56.094+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:05:56.093+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:05:56.436+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:05:56.434+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:05:56.437+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:05:56.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.364 seconds
[2025-04-05T16:06:26.728+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:06:26.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:06:26.731+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:06:26.730+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:06:27.076+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:06:27.074+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:06:27.077+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:06:27.087+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.364 seconds
[2025-04-05T16:06:57.348+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:06:57.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:06:57.351+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:06:57.350+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:06:57.579+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:06:57.576+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:06:57.579+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:06:57.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.251 seconds
[2025-04-05T16:07:56.924+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:07:56.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:07:56.933+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:07:56.933+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:07:58.833+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:07:58.829+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:07:58.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:07:58.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 1.948 seconds
[2025-04-05T16:08:29.072+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:08:29.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:08:29.074+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:08:29.074+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:08:29.316+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:08:29.313+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:08:29.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:08:29.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.262 seconds
[2025-04-05T16:08:59.370+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:08:59.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:08:59.376+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:08:59.375+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:08:59.638+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:08:59.635+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:08:59.639+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:08:59.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.288 seconds
[2025-04-05T16:09:02.580+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:09:02.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:09:02.583+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:09:02.583+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:09:02.966+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:09:02.963+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:09:02.966+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:09:02.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.405 seconds
[2025-04-05T16:09:11.780+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:09:11.781+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:09:11.783+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:09:11.783+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:09:12.129+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:09:12.126+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:09:12.129+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:09:12.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.366 seconds
[2025-04-05T16:09:42.340+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:09:42.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:09:42.342+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:09:42.342+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:09:42.697+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:09:42.695+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:09:42.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:09:42.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.373 seconds
[2025-04-05T16:10:12.925+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:10:12.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:10:12.928+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:10:12.927+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:10:13.270+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:10:13.268+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:10:13.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:10:13.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.360 seconds
[2025-04-05T16:10:43.497+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:10:43.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:10:43.500+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:10:43.499+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:10:43.925+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:10:43.923+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:10:43.926+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:10:43.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.446 seconds
[2025-04-05T16:11:14.213+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:11:14.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:11:14.216+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:11:14.216+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:11:14.787+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:11:14.784+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:11:14.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:11:14.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.594 seconds
[2025-04-05T16:11:45.065+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:11:45.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:11:45.069+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:11:45.069+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:11:45.304+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:11:45.301+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:11:45.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:11:45.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.261 seconds
[2025-04-05T16:12:15.570+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:12:15.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:12:15.573+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:12:15.572+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:12:15.907+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:12:15.905+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:12:15.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:12:15.919+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.355 seconds
[2025-04-05T16:12:46.187+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:12:46.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-04-05T16:12:46.190+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:12:46.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:12:46.606+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:12:46.603+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 6, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-04-05T16:12:46.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-04-05T16:12:46.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.436 seconds
